# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.IntegerField(default=0)),
                ('img', models.CharField(max_length=500, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('rss', models.CharField(max_length=1024, null=True)),
                ('content', models.TextField()),
                ('content_show', models.TextField(null=True, verbose_name='正文显示')),
                ('add_date', models.DateTimeField()),
                ('counts', models.IntegerField(default=0)),
                ('is_show', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='MyPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('img', models.IntegerField(null=True)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mypic',
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=200)),
                ('add_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pic',
            },
        ),
        migrations.CreateModel(
            name='PicType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('img', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'pic_type',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
                ('content', models.TextField()),
                ('content_show', models.TextField(null=True, verbose_name='show')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wiki',
            },
        ),
        migrations.CreateModel(
            name='WikiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wiki_type',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('add_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'word',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('explain', models.CharField(max_length=300, null=True)),
                ('phonetic', models.CharField(max_length=100, null=True)),
                ('seq', models.CharField(max_length=300, null=True)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'words',
            },
        ),
    ]
