# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.IntegerField(default=0)),
                ('img', models.CharField(max_length=500, null=True)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('rss', models.CharField(max_length=1024, null=True)),
                ('content', models.TextField()),
                ('content_show', models.TextField(null=True, verbose_name='正文显示')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('counts', models.IntegerField(default=0)),
                ('is_show', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'blog',
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Blog')),
            ],
            options={
                'db_table': 'blog_tag',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.AddField(
            model_name='blogtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Tag'),
        ),
    ]
