# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtag',
            name='blog',
            field=models.ForeignKey(default=datetime.datetime(2016, 4, 27, 13, 6, 42, 712349, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='mysite.Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogtag',
            name='tag',
            field=models.ForeignKey(default=datetime.datetime(2016, 4, 27, 13, 6, 53, 600972, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='mysite.Tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='word',
            field=models.ForeignKey(default=datetime.datetime(2016, 4, 27, 13, 7, 27, 524912, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='mysite.Word'),
            preserve_default=False,
        ),
    ]
