# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20160427_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='word',
        ),
        migrations.AlterField(
            model_name='pic',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
