# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20160427_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pictype',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wikitype',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='add_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='words',
            name='add_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
